name: Docker build and push

on:
  pull_request:
    branches: [ main ]
    paths: [ 'llvm/**' ]
  push:
    branches: [ main ]
    paths: [ 'llvm/**' ]
  schedule:
    # https://crontab.guru/weekly
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  docker:
    strategy:
      fail-fast: false
      matrix:
        platform: ['linux/amd64'] # ['linux/amd64', 'linux/arm64']

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Get latest LLVM release
      id: llvm
      uses: pozetroninc/github-action-get-latest-release@v0.5.0
      with:
        owner: llvm
        repo: llvm-project
        excludes: draft #, prerelease

    - name: ACR login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZ_ACR_NAME }}
        username: ${{ secrets.AZ_SP_CLIENT_ID }}
        password: ${{ secrets.AZ_SP_CLIENT_SECRET }}

    - name: Docker metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ secrets.AZ_ACR_NAME }}/accera-llvm-ubuntu
        flavor: |
          suffix=-${{ steps.llvm.outputs.release }}
          latest=true

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
   
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: ${{ matrix.platform }}  
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: ${{ github.event_name != 'pull_request' }}
        build-args: LLVM_RELEASE=${{ steps.llvm.outputs.release }}

    - name: Upload build logs
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: accera-llvm-build-logs
        path: /opt/vcpkg/buildtrees/accera-llvm/*.log
