name: llvm ubuntu build

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Docker metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: lisaong/accera-llvm-ubuntu

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Dockerhub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: ${{ github.event_name != 'pull_request' }}
