name: llvm ubuntu build

on:
  pull_request:
    branches: [ main ]
    paths: [ 'llvm/**' ]
  push:
    branches: [ main ]
    paths: [ 'llvm/**' ]
  schedule:
    # https://crontab.guru/weekly
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Get latest LLVM release
      id: llvm
      uses: pozetroninc/github-action-get-latest-release@v0.5.0
      with:
        owner: llvm
        repo: llvm-project
        excludes: draft #, prerelease

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Dockerhub login
      uses: docker/login-action@v1
      with:
        username: 'lisaong'
        password: ${{ secrets['DOCKER_PASSWORD'] }}

    - name: Docker metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: lisaong/accera-llvm-ubuntu
        flavor: |
          suffix=-${{ steps.llvm.outputs.release }}
          latest=true

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: ${{ github.event_name != 'pull_request' }}
        build-args: LLVM_RELEASE=${{ steps.llvm.outputs.release }}

    - name: Dockerhub login
      uses: docker/login-action@v1
      with:
        username: 'acceracontainers'
        password: ${{ secrets['ACCERA_DOCKER_PASSWORD'] }}

    - name: Docker metadata
      id: meta_accera
      uses: docker/metadata-action@v3
      with:
        images: acceracontainers/accera-llvm-ubuntu
        flavor: |
          suffix=-${{ steps.llvm.outputs.release }}
          latest=true

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: ${{ steps.meta_accera.outputs.tags }}
        labels: ${{ steps.meta_accera.outputs.labels }}
        push: ${{ github.event_name != 'pull_request' }}
        build-args: LLVM_RELEASE=${{ steps.llvm.outputs.release }}

    - name: Upload build logs
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: accera-llvm-build-logs
        path: /opt/vcpkg/buildtrees/accera-llvm/*.log
