name: llvm ubuntu build

on:
  # pull_request:
  #   branches: [ main ]
  push:
    branches:
      - 'main'
  schedule:
    # https://crontab.guru/weekly
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Get latest LLVM release
      id: llvm
      uses: pozetroninc/github-action-get-latest-release@v0.5.0
      with:
        owner: llvm
        repo: llvm-project
        excludes: prerelease, draft

    - name: Docker metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: lisaong/accera-llvm-ubuntu
        flavor: |
          suffix=-${{ steps.llvm.outputs.release }}
          latest=true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Dockerhub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: ${{ github.event_name != 'pull_request' }}
        build-args: LLVM_RELEASE=${{ steps.llvm.outputs.release }}

    - name: Upload build logs
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: accera-llvm-build-logs
        path: /opt/vcpkg/buildtrees/accera-llvm/*.log

  debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Get latest LLVM release
      id: llvm
      uses: pozetroninc/github-action-get-latest-release@v0.5.0
      with:
        owner: llvm
        repo: llvm-project
        excludes: prerelease, draft

    - name: Docker metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: lisaong/accera-llvm-ubuntu-dbg
        flavor: |
          suffix=-${{ steps.llvm.outputs.release }}
          latest=true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Dockerhub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: ${{ github.event_name != 'pull_request' }}
        build-args: |
          LLVM_RELEASE=${{ steps.llvm.outputs.release }}
          LLVM_BUILD_TYPE=debug
      
    - name: Upload build logs
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: accera-llvm-dbg-build-logs
        path: /opt/vcpkg/buildtrees/accera-llvm/*.log