name: Repro

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: setup
        run: |
          external\vcpkg\bootstrap-vcpkg.bat
          external\vcpkg\vcpkg.exe install catch2:x64-windows

      - name: build
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -G"Visual Studio 17 2022" -Ax64
          cmake --build . --config Release



